import { memo } from 'react';

interface Props {
  isDarkMode: boolean;
  goToMainView: () => void;
}

export const SecurityView = memo(({ isDarkMode, goToMainView }: Props) => (
  <div className={`min-h-screen bg-gradient-to-b from-gray-950 via-gray-900 to-black text-gray-100 ${isDarkMode ? 'dark' : ''}`}>
      <div className="max-w-4xl mx-auto px-6 py-10">
        <header className="flex items-center justify-between mb-8">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 bg-cyan-600 rounded-lg flex items-center justify-center overflow-hidden flex-shrink-0">
              <img src="/logoCYAN.png" alt="CYAN Logo" className="w-full h-full object-cover" />
            </div>
            <div>
              <div className="text-sm font-semibold text-cyan-300">CYAN AI</div>
              <div className="text-xs text-gray-400">Dedicated Voice Copyright &amp; Cloning Policy</div>
            </div>
          </div>
          <button
            type="button"
            onClick={goToMainView}
            className="text-xs font-medium text-gray-400 hover:text-gray-100"
          >
            Back to site
          </button>
        </header>
        <main className="bg-gray-900/80 border border-gray-800 rounded-2xl shadow-xl px-6 py-6 md:px-8 md:py-8">
          <div className="flex items-start justify-between gap-4 border-b border-gray-800 pb-4 mb-6">
            <div>
              <div className="text-base md:text-lg font-semibold text-white">
                CYAN AI: DEDICATED VOICE COPYRIGHT &amp; CLONING POLICY
              </div>
              <div className="mt-1 text-xs text-gray-400">Effective Date: January 28, 2026</div>
            </div>
          </div>
          <div className="space-y-5 text-sm leading-relaxed">
            <div>
              <div className="font-semibold text-white">1. LEGAL OWNERSHIP OF VOICE DATA</div>
              <p className="mt-1 text-gray-300">
                CYAN AI (the &quot;Company&quot;) recognizes that a person&apos;s voice is a core part of their
                personal identity and intellectual property.
              </p>
              <ul className="mt-2 list-disc list-inside text-gray-300 space-y-1">
                <li>
                  User-Provided Content: By uploading audio for the purpose of &quot;Voice Cloning,&quot; the User
                  represents and warrants that they are the legal owner of the voice or have obtained express, written,
                  and notarized consent from the owner of the voice.
                </li>
                <li>
                  CYAN’s Role: CYAN acts strictly as a Service Provider and a neutral processing platform. We do not
                  claim ownership over any voice models generated through our Service.
                </li>
              </ul>
            </div>
            <div>
              <div className="font-semibold text-white">2. VOICE CLONING COMPLIANCE &amp; CONSENT (VCC)</div>
              <p className="mt-1 text-gray-300">
                The use of the Customized Voice Cloning capability (available in the Executive Pro Plan) is strictly
                subject to the following conditions:
              </p>
              <ul className="mt-2 list-disc list-inside text-gray-300 space-y-1">
                <li>
                  The &quot;Self-Cloning&quot; Rule: Users are encouraged to clone only their own voices for
                  professional use in meetings and webinars.
                </li>
                <li>
                  Prohibition of Celebrity/Public Figure Cloning: Users are strictly prohibited from uploading audio of
                  celebrities, politicians, or any public figure for the purpose of voice cloning, regardless of whether
                  the source material is publicly available.
                </li>
                <li>
                  Verification Rights: CYAN reserves the right, at its sole discretion, to request proof of consent or
                  identity verification before activating a Customized Voice Clone.
                </li>
              </ul>
            </div>
            <div>
              <div className="font-semibold text-white">3. INTELLECTUAL PROPERTY RIGHTS (IPR)</div>
              <ul className="mt-2 list-disc list-inside text-gray-300 space-y-1">
                <li>
                  Output Rights: Subject to the User’s compliance with these terms, the User owns the rights to the
                  translated audio output generated by the Service.
                </li>
                <li>
                  Model Training Data: CYAN does not use User-provided voice samples to train its core proprietary AI
                  models. Voice samples are used exclusively to generate a temporary or permanent voice profile for that
                  specific User&apos;s account.
                </li>
              </ul>
            </div>
            <div>
              <div className="font-semibold text-white">4. PROHIBITED USES &amp; &quot;DEEPFAKE&quot; PREVENTION</div>
              <p className="mt-1 text-gray-300">
                CYAN maintains a Zero-Tolerance Policy regarding the following activities:
              </p>
              <ul className="mt-2 list-disc list-inside text-gray-300 space-y-1">
                <li>
                  Impersonation with Malicious Intent: Using a cloned voice to commit fraud, gain unauthorized access
                  to financial accounts (Voice Biometrics fraud), or mislead any third party.
                </li>
                <li>
                  Defamation: Creating content that harms the reputation of any individual through synthetic voice
                  output.
                </li>
                <li>
                  Electoral Interference: Using the Service to create deceptive content related to elections or
                  political processes.
                </li>
                <li>
                  Violation of Publicity Rights: Any use that violates the &quot;Right of Publicity&quot; under
                  international laws.
                </li>
              </ul>
            </div>
            <div>
              <div className="font-semibold text-white">5. MONITORING AND ENFORCEMENT</div>
              <ul className="mt-2 list-disc list-inside text-gray-300 space-y-1">
                <li>
                  Automated Detection: CYAN utilizes advanced audio watermarking and metadata tracking (in
                  collaboration with providers like ElevenLabs) to identify synthetic speech generated by our platform.
                </li>
                <li>
                  Account Termination: Any violation of this Voice Copyright Policy will result in an immediate and
                  permanent ban from the Service without a refund.
                </li>
                <li>
                  Legal Cooperation: CYAN will cooperate fully with law enforcement agencies in any investigation
                  involving the misuse of our voice cloning technology for illegal activities.
                </li>
              </ul>
            </div>
            <div>
              <div className="font-semibold text-white">6. INDEMNIFICATION</div>
              <p className="mt-1 text-gray-300">
                The User agrees to indemnify, defend, and hold harmless CYAN AI, its founders, and its technology
                partners (ElevenLabs, Azure, Google) from any and all claims, damages, or legal fees arising from the
                User’s unauthorized use of a third party’s voice.
              </p>
            </div>
            <div>
              <div className="font-semibold text-white">7. LIMITATION OF LIABILITY REGARDING THIRD-PARTY MODELS</div>
              <p className="mt-1 text-gray-300">
                CYAN utilizes third-party AI models (e.g., ElevenLabs) for voice synthesis. While CYAN implements its
                own safety layers, the User also agrees to be bound by the ElevenLabs Terms of Service regarding
                acceptable voice use. Any changes in third-party policies that restrict certain voices will be passed on
                to the User immediately.
              </p>
            </div>
            <div>
              <div className="font-semibold text-white">8. INCIDENT RESPONSE &amp; INVESTIGATION</div>
              <p className="mt-1 text-gray-300">
                If CYAN reasonably suspects that the voice cloning capabilities of the Service are being misused,
                we may take immediate steps to protect affected individuals and the integrity of the platform.
              </p>
              <ul className="mt-2 list-disc list-inside text-gray-300 space-y-1">
                <li>Initial Action: We may temporarily suspend or restrict access to specific voice models or user accounts while an investigation is conducted.</li>
                <li>Investigation: CYAN may review technical logs, consult with technology partners, and request additional information from the User.</li>
                <li>Outcome: Following investigation, CYAN may restore access, impose additional restrictions, or permanently terminate the account in line with this Policy and applicable law.</li>
              </ul>
            </div>
            <div>
              <div className="font-semibold text-white">9. USER COOPERATION &amp; APPEALS</div>
              <p className="mt-1 text-gray-300">
                Users agree to cooperate in good faith with CYAN&apos;s efforts to prevent abuse of voice technologies.
              </p>
              <ul className="mt-2 list-disc list-inside text-gray-300 space-y-1">
                <li>Information Requests: CYAN may request documentation or clarification to verify rights to a specific voice or use case.</li>
                <li>Appeal Process: If you believe your account or voice model has been restricted in error, you may contact support with relevant evidence for review.</li>
              </ul>
            </div>
            <div>
              <div className="font-semibold text-white">10. RELATIONSHIP TO PRIVACY &amp; SECURITY POLICIES</div>
              <p className="mt-1 text-gray-300">
                This Dedicated Voice Copyright &amp; Cloning Policy operates alongside CYAN&apos;s general Privacy
                Policy and Terms of Service.
              </p>
              <ul className="mt-2 list-disc list-inside text-gray-300 space-y-1">
                <li>Zero-Retention: Except where required for security or legal reasons, audio processed through the Service is subject to CYAN&apos;s zero-retention commitments described in the Privacy Policy.</li>
                <li>Policy Updates: CYAN may update this Policy periodically to reflect evolving legal, ethical, and technological standards in synthetic media and voice AI.</li>
              </ul>
            </div>
          </div>
        </main>
      </div>
    </div>
));
